/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/nPayk81XNqJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import axios from "axios";
import useSWR from "swr";


export const Component = async () => {

  return (
    (<div className="flex flex-col min-h-screen bg-muted/40">
      <header className="bg-background border-b px-4 sm:px-6 flex items-center h-16">
        <div className="flex items-center gap-2">
          <GarudaIcon className="w-6 h-6" />
          <h1 className="text-lg font-semibold">Garuda Dashboard</h1>
        </div>
        <p className="ml-4 text-muted-foreground text-sm">Manage and monitor all your API endpoints.</p>
      </header>
      <main className="flex-1 p-4 sm:p-6">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>API</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Endpoint</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
          {data.map((item) => (
            <TableRow key={item.endpoint}>
              <TableCell>
                {/* ... API name display */}
              </TableCell>
              <TableCell>
                {/* ... Status display */}
              </TableCell>
              <TableCell>
                <p className="text-muted-foreground">{item.endpoint}</p>
              </TableCell>
            </TableRow>
          ))}
            {/* <TableRow>
              <TableCell>
                <div className="flex items-center gap-2">
                  <PiIcon className="w-4 h-4" />
                  <span>Products API</span>
                </div>
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <Badge variant="secondary" className="bg-green-400">
                    Healthy
                  </Badge>
                  <p className="text-muted-foreground">The API is currently functioning as expected.</p>
                </div>
              </TableCell>
              <TableCell>
                <p className="text-muted-foreground">https://api.acme.com/v1/products</p>
              </TableCell>
            </TableRow> */}
          </TableBody>
        </Table>
      </main>
    </div>)
  );
}

function PiIcon(props) {
  return (
    (<img src="" />)
  );
}

function GarudaIcon(props){
  return(
    (<img src="https://i.ibb.co/wc49JVH/Firefly-garuda-logo-minimal-sharp-eagle-sharper-eyes-protecting-in-darkness-only-border-shine-g-1-re.png" width="10%" />)
  )
}

