-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.api
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    path text COLLATE pg_catalog."default",
    parameters jsonb,
    created_time numeric,
    req_type character varying(255) COLLATE pg_catalog."default",
    inventory serial NOT NULL,
    responses jsonb,
    CONSTRAINT api_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.application
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT application_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    path text COLLATE pg_catalog."default",
    app_id serial NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (name, app_id),
    CONSTRAINT unique_id UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS public.model
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    fields jsonb,
    app_id serial NOT NULL,
    CONSTRAINT model_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.api
    ADD CONSTRAINT fk_inventory FOREIGN KEY (inventory)
    REFERENCES public.inventory (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_app_id FOREIGN KEY (app_id)
    REFERENCES public.application (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.model
    ADD CONSTRAINT model_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.application (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
